services:
  # Backend/API
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rhf-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://rho:secret/rhf?sslmode=disable
      JWT_SECRET: ${JWT_SECRET:-seu_jwt_secret_aqui_mudeme_em_producao}
      TZ: America/Rio_Branco
    ports:
      - "3001:3001"
    networks:
      - rhf-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend com SSL
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: rhf-client
    restart: unless-stopped
    environment:
      TZ: America/Rio_Branco
    ports:
      - "80:80"      # HTTP (redireciona para HTTPS)
      - "443:443"    # HTTPS
    volumes:
    # mentioned in dokploy file
      - ./nginx-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    networks:
      - rhf-network

networks:
  rhf-network:
    name: rhf-network
    driver: bridge
